/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package itp_library;

import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import static itp_library.Dashboard.content;
/**
 *
 * @author Antonio
 */
public class UpBooks extends javax.swing.JPanel {

    Connect conn;
    Connection reg;
    boolean edition;
    String origId;
    /**
     * Creates new form Principal
     */
    public UpBooks() {
        initComponents();
        conn = new Connect();
        reg = conn.getConnection();
        edition = false;
    }
    
    public UpBooks(String bid, String btitle, String bdate, String bauthor, String bcategory, String bedit, String blang, String bpages, String bdesc, String bejem, String bstock, String bavai){
        initComponents();
        conn = new Connect();
        reg = conn.getConnection();
        edition = true;
        
        origId = bid;
        id.setText(bid);
        title.setText(btitle);
        date.setText(bdate);
        author.setText(bauthor);
        category.setText(bcategory);
        edit.setText(bedit);
        lang.setText(blang);
        pages.setText(bpages);
        descr.setText(bdesc);
        ejem.setText(bejem);
        stock.setText(bstock);
        available.setText(bavai);
        
        jLabel1.setText("Guardar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        button = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Text3 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        Text6 = new javax.swing.JLabel();
        title = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        Text7 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        Text8 = new javax.swing.JLabel();
        author = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        Text9 = new javax.swing.JLabel();
        category = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        edit = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        Text10 = new javax.swing.JLabel();
        Text4 = new javax.swing.JLabel();
        lang = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        Text11 = new javax.swing.JLabel();
        pages = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        Text12 = new javax.swing.JLabel();
        descr = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        Text13 = new javax.swing.JLabel();
        stock = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        Text14 = new javax.swing.JLabel();
        ejem = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        available = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        Text15 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Title.setText("Subir nuevo Libro");
        add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 10, 350));

        button.setBackground(new java.awt.Color(18, 90, 173));
        button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonMousePressed(evt);
            }
        });
        button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Subir");
        button.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, 30));

        add(button, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 260, 50));

        Text3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text3.setText("Libro ID");
        add(Text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        id.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        id.setForeground(new java.awt.Color(102, 102, 102));
        id.setText("Ingrese el ID del Libro");
        id.setBorder(null);
        id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                idMousePressed(evt);
            }
        });
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 260, 30));

        jSeparator4.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator4.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 260, 10));

        Text6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text6.setText("Título");
        add(Text6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        title.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        title.setForeground(new java.awt.Color(102, 102, 102));
        title.setText("Ingrese el Título");
        title.setBorder(null);
        title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                titleMousePressed(evt);
            }
        });
        title.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleActionPerformed(evt);
            }
        });
        add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 260, 30));

        jSeparator7.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator7.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 260, 10));

        Text7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text7.setText("Fecha de Publicación");
        add(Text7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        date.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        date.setForeground(new java.awt.Color(102, 102, 102));
        date.setText("Ingrese la Fecha de Publicación");
        date.setBorder(null);
        date.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dateMousePressed(evt);
            }
        });
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });
        add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 260, 30));

        jSeparator8.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator8.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 260, 10));

        Text8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text8.setText("Autor");
        add(Text8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        author.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        author.setForeground(new java.awt.Color(102, 102, 102));
        author.setText("Ingrese el nombre del Autor/es");
        author.setBorder(null);
        author.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                authorMousePressed(evt);
            }
        });
        author.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorActionPerformed(evt);
            }
        });
        add(author, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 260, 30));

        jSeparator9.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator9.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 260, 10));

        Text9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text9.setText("Categoría");
        add(Text9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        category.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        category.setForeground(new java.awt.Color(102, 102, 102));
        category.setText("Ingrese la Categoría del Libro");
        category.setBorder(null);
        category.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                categoryMousePressed(evt);
            }
        });
        category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryActionPerformed(evt);
            }
        });
        add(category, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 260, 30));

        jSeparator10.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator10.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 260, 10));

        edit.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        edit.setForeground(new java.awt.Color(102, 102, 102));
        edit.setText("Ingrese la edición");
        edit.setBorder(null);
        edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editMousePressed(evt);
            }
        });
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 260, 30));

        jSeparator11.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator11.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 260, 10));

        Text10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text10.setText("Edición");
        add(Text10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        Text4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text4.setText("Idioma");
        add(Text4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, -1));

        lang.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lang.setForeground(new java.awt.Color(102, 102, 102));
        lang.setText("Ingrese el idioma del Libro");
        lang.setBorder(null);
        lang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                langMousePressed(evt);
            }
        });
        lang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                langActionPerformed(evt);
            }
        });
        add(lang, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 260, 30));

        jSeparator5.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator5.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 260, 10));

        Text11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text11.setText("Páginas");
        add(Text11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, -1, -1));

        pages.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        pages.setForeground(new java.awt.Color(102, 102, 102));
        pages.setText("Ingrese la cantidad de páginas totales");
        pages.setBorder(null);
        pages.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pagesMousePressed(evt);
            }
        });
        pages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagesActionPerformed(evt);
            }
        });
        add(pages, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 260, 30));

        jSeparator12.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator12.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 260, 10));

        Text12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text12.setText("Descripción");
        add(Text12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, -1, -1));

        descr.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        descr.setForeground(new java.awt.Color(102, 102, 102));
        descr.setText("Ingrese la descripción del Libro");
        descr.setBorder(null);
        descr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                descrMousePressed(evt);
            }
        });
        descr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descrActionPerformed(evt);
            }
        });
        add(descr, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 260, 30));

        jSeparator13.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator13.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 260, 10));

        Text13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text13.setText("Stock");
        add(Text13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, -1, -1));

        stock.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        stock.setForeground(new java.awt.Color(102, 102, 102));
        stock.setText("Cantidad Total");
        stock.setBorder(null);
        stock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                stockMousePressed(evt);
            }
        });
        stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockActionPerformed(evt);
            }
        });
        add(stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 80, 30));

        jSeparator14.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator14.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 80, 10));

        Text14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text14.setText("Ejemplares");
        add(Text14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, -1, -1));

        ejem.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        ejem.setForeground(new java.awt.Color(102, 102, 102));
        ejem.setText("Ingrese la cantidad de ejemplares");
        ejem.setBorder(null);
        ejem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ejemMousePressed(evt);
            }
        });
        ejem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejemActionPerformed(evt);
            }
        });
        add(ejem, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 260, 30));

        jSeparator15.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator15.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 260, 10));

        available.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        available.setForeground(new java.awt.Color(102, 102, 102));
        available.setText("Cantidad a prestar");
        available.setBorder(null);
        available.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                availableMousePressed(evt);
            }
        });
        available.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availableActionPerformed(evt);
            }
        });
        add(available, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, 100, 30));

        jSeparator16.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator16.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, 100, 10));

        Text15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text15.setText("Disponibles");
        add(Text15, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseEntered
        setColor(button);
    }//GEN-LAST:event_buttonMouseEntered

    private void buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseExited
        resetColor(button);
    }//GEN-LAST:event_buttonMouseExited

    private void idMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idMousePressed
       if(id.getText().equals("Ingrese el ID del Libro"))
        id.setText("");
       if(title.getText().equals("") || title.getText() == null || title.getText().equals(" "))
        title.setText("Ingrese el Título");
       if(date.getText().equals("") || date.getText() == null || date.getText().equals(" "))
        date.setText("Ingrese la Fecha de Publicación");
       if(author.getText().equals("") || author.getText() == null || author.getText().equals(" "))
        author.setText("Ingrese el nombre del Autor/es");
       if(category.getText().equals("") || category.getText() == null || category.getText().equals(" "))
        category.setText("Ingrese la Categoría del Libro");
       if(edit.getText().equals("") || edit.getText() == null || edit.getText().equals(" "))
        edit.setText("Ingrese la edición");
       if(lang.getText().equals("") || lang.getText() == null || lang.getText().equals(" "))
        lang.setText("Ingrese el idioma del Libro");
       if(pages.getText().equals("") || pages.getText() == null || pages.getText().equals(" "))
        pages.setText("Ingrese la cantidad de páginas totales");
       if(descr.getText().equals("") || descr.getText() == null || descr.getText().equals(" "))
        descr.setText("Ingrese la descripción del Libro");
       if(stock.getText().equals("") || stock.getText() == null || stock.getText().equals(" "))
        stock.setText("Cantidad Total");
       if(available.getText().equals("") || available.getText() == null || available.getText().equals(" "))
        available.setText("Cantidad a prestar");
       if(ejem.getText().equals("") || ejem.getText() == null || ejem.getText().equals(" "))
        ejem.setText("Ingrese la cantidad de ejemplares");
    }//GEN-LAST:event_idMousePressed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void titleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleMousePressed
        if(title.getText().equals("Ingrese el Título"))
        title.setText("");
       if(id.getText().equals("") || id.getText() == null || id.getText().equals(" "))
        id.setText("Ingrese el ID del Libro");
       if(date.getText().equals("") || date.getText() == null || date.getText().equals(" "))
        date.setText("Ingrese la Fecha de Publicación");
       if(author.getText().equals("") || author.getText() == null || author.getText().equals(" "))
        author.setText("Ingrese el nombre del Autor/es");
       if(category.getText().equals("") || category.getText() == null || category.getText().equals(" "))
        category.setText("Ingrese la Categoría del Libro");
       if(edit.getText().equals("") || edit.getText() == null || edit.getText().equals(" "))
        edit.setText("Ingrese la edición");
       if(lang.getText().equals("") || lang.getText() == null || lang.getText().equals(" "))
        lang.setText("Ingrese el idioma del Libro");
       if(pages.getText().equals("") || pages.getText() == null || pages.getText().equals(" "))
        pages.setText("Ingrese la cantidad de páginas totales");
       if(descr.getText().equals("") || descr.getText() == null || descr.getText().equals(" "))
        descr.setText("Ingrese la descripción del Libro");
       if(stock.getText().equals("") || stock.getText() == null || stock.getText().equals(" "))
        stock.setText("Cantidad Total");
       if(available.getText().equals("") || available.getText() == null || available.getText().equals(" "))
        available.setText("Cantidad a prestar");
       if(ejem.getText().equals("") || ejem.getText() == null || ejem.getText().equals(" "))
        ejem.setText("Ingrese la cantidad de ejemplares");
    }//GEN-LAST:event_titleMousePressed

    private void titleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleActionPerformed

    private void dateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateMousePressed
        if(date.getText().equals("Ingrese la Fecha de Publicación"))
        date.setText("");
       if(id.getText().equals("") || id.getText() == null || id.getText().equals(" "))
        id.setText("Ingrese el ID del Libro");
       if(title.getText().equals("") || title.getText() == null || title.getText().equals(" "))
        title.setText("Ingrese el Título");
       if(author.getText().equals("") || author.getText() == null || author.getText().equals(" "))
        author.setText("Ingrese el nombre del Autor/es");
       if(category.getText().equals("") || category.getText() == null || category.getText().equals(" "))
        category.setText("Ingrese la Categoría del Libro");
       if(edit.getText().equals("") || edit.getText() == null || edit.getText().equals(" "))
        edit.setText("Ingrese la edición");
       if(lang.getText().equals("") || lang.getText() == null || lang.getText().equals(" "))
        lang.setText("Ingrese el idioma del Libro");
       if(pages.getText().equals("") || pages.getText() == null || pages.getText().equals(" "))
        pages.setText("Ingrese la cantidad de páginas totales");
       if(descr.getText().equals("") || descr.getText() == null || descr.getText().equals(" "))
        descr.setText("Ingrese la descripción del Libro");
       if(stock.getText().equals("") || stock.getText() == null || stock.getText().equals(" "))
        stock.setText("Cantidad Total");
       if(available.getText().equals("") || available.getText() == null || available.getText().equals(" "))
        available.setText("Cantidad a prestar");
       if(ejem.getText().equals("") || ejem.getText() == null || ejem.getText().equals(" "))
        ejem.setText("Ingrese la cantidad de ejemplares");
    }//GEN-LAST:event_dateMousePressed

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed

    private void authorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_authorMousePressed
        if(author.getText().equals("Ingrese el nombre del Autor/es"))
        author.setText("");
       if(id.getText().equals("") || id.getText() == null || id.getText().equals(" "))
        id.setText("Ingrese el ID del Libro");
       if(title.getText().equals("") || title.getText() == null || title.getText().equals(" "))
        title.setText("Ingrese el Título");
       if(date.getText().equals("") || date.getText() == null || date.getText().equals(" "))
        date.setText("Ingrese la Fecha de Publicación");
       if(category.getText().equals("") || category.getText() == null || category.getText().equals(" "))
        category.setText("Ingrese la Categoría del Libro");
       if(edit.getText().equals("") || edit.getText() == null || edit.getText().equals(" "))
        edit.setText("Ingrese la edición");
       if(lang.getText().equals("") || lang.getText() == null || lang.getText().equals(" "))
        lang.setText("Ingrese el idioma del Libro");
       if(pages.getText().equals("") || pages.getText() == null || pages.getText().equals(" "))
        pages.setText("Ingrese la cantidad de páginas totales");
       if(descr.getText().equals("") || descr.getText() == null || descr.getText().equals(" "))
        descr.setText("Ingrese la descripción del Libro");
       if(stock.getText().equals("") || stock.getText() == null || stock.getText().equals(" "))
        stock.setText("Cantidad Total");
       if(available.getText().equals("") || available.getText() == null || available.getText().equals(" "))
        available.setText("Cantidad a prestar");
       if(ejem.getText().equals("") || ejem.getText() == null || ejem.getText().equals(" "))
        ejem.setText("Ingrese la cantidad de ejemplares");
    }//GEN-LAST:event_authorMousePressed

    private void authorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_authorActionPerformed

    private void categoryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoryMousePressed
        if(category.getText().equals("Ingrese la Categoría del Libro"))
        category.setText("");
       if(id.getText().equals("") || id.getText() == null || id.getText().equals(" "))
        id.setText("Ingrese el ID del Libro");
       if(title.getText().equals("") || title.getText() == null || title.getText().equals(" "))
        title.setText("Ingrese el Título");
       if(date.getText().equals("") || date.getText() == null || date.getText().equals(" "))
        date.setText("Ingrese la Fecha de Publicación");
       if(author.getText().equals("") || author.getText() == null || author.getText().equals(" "))
        author.setText("Ingrese el nombre del Autor/es");
       if(edit.getText().equals("") || edit.getText() == null || edit.getText().equals(" "))
        edit.setText("Ingrese la edición");
       if(lang.getText().equals("") || lang.getText() == null || lang.getText().equals(" "))
        lang.setText("Ingrese el idioma del Libro");
       if(pages.getText().equals("") || pages.getText() == null || pages.getText().equals(" "))
        pages.setText("Ingrese la cantidad de páginas totales");
       if(descr.getText().equals("") || descr.getText() == null || descr.getText().equals(" "))
        descr.setText("Ingrese la descripción del Libro");
       if(stock.getText().equals("") || stock.getText() == null || stock.getText().equals(" "))
        stock.setText("Cantidad Total");
       if(available.getText().equals("") || available.getText() == null || available.getText().equals(" "))
        available.setText("Cantidad a prestar");
       if(ejem.getText().equals("") || ejem.getText() == null || ejem.getText().equals(" "))
        ejem.setText("Ingrese la cantidad de ejemplares");
    }//GEN-LAST:event_categoryMousePressed

    private void categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryActionPerformed

    private void editMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMousePressed
        if(edit.getText().equals("Ingrese la edición"))
        edit.setText("");
       if(id.getText().equals("") || id.getText() == null || id.getText().equals(" "))
        id.setText("Ingrese el ID del Libro");
       if(title.getText().equals("") || title.getText() == null || title.getText().equals(" "))
        title.setText("Ingrese el Título");
       if(date.getText().equals("") || date.getText() == null || date.getText().equals(" "))
        date.setText("Ingrese la Fecha de Publicación");
       if(author.getText().equals("") || author.getText() == null || author.getText().equals(" "))
        author.setText("Ingrese el nombre del Autor/es");
       if(category.getText().equals("") || category.getText() == null || category.getText().equals(" "))
        category.setText("Ingrese la Categoría del Libro");
       if(lang.getText().equals("") || lang.getText() == null || lang.getText().equals(" "))
        lang.setText("Ingrese el idioma del Libro");
       if(pages.getText().equals("") || pages.getText() == null || pages.getText().equals(" "))
        pages.setText("Ingrese la cantidad de páginas totales");
       if(descr.getText().equals("") || descr.getText() == null || descr.getText().equals(" "))
        descr.setText("Ingrese la descripción del Libro");
       if(stock.getText().equals("") || stock.getText() == null || stock.getText().equals(" "))
        stock.setText("Cantidad Total");
       if(available.getText().equals("") || available.getText() == null || available.getText().equals(" "))
        available.setText("Cantidad a prestar");
       if(ejem.getText().equals("") || ejem.getText() == null || ejem.getText().equals(" "))
        ejem.setText("Ingrese la cantidad de ejemplares");
    }//GEN-LAST:event_editMousePressed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editActionPerformed

    private void langMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_langMousePressed
       if(lang.getText().equals("Ingrese el idioma del Libro"))
        lang.setText("");
       if(id.getText().equals("") || id.getText() == null || id.getText().equals(" "))
        id.setText("Ingrese el ID del Libro");
       if(title.getText().equals("") || title.getText() == null || title.getText().equals(" "))
        title.setText("Ingrese el Título");
       if(date.getText().equals("") || date.getText() == null || date.getText().equals(" "))
        date.setText("Ingrese la Fecha de Publicación");
       if(author.getText().equals("") || author.getText() == null || author.getText().equals(" "))
        author.setText("Ingrese el nombre del Autor/es");
       if(category.getText().equals("") || category.getText() == null || category.getText().equals(" "))
        category.setText("Ingrese la Categoría del Libro");
       if(edit.getText().equals("") || edit.getText() == null || edit.getText().equals(" "))
        edit.setText("Ingrese la edición");
       if(pages.getText().equals("") || pages.getText() == null || pages.getText().equals(" "))
        pages.setText("Ingrese la cantidad de páginas totales");
       if(descr.getText().equals("") || descr.getText() == null || descr.getText().equals(" "))
        descr.setText("Ingrese la descripción del Libro");
       if(stock.getText().equals("") || stock.getText() == null || stock.getText().equals(" "))
        stock.setText("Cantidad Total");
       if(available.getText().equals("") || available.getText() == null || available.getText().equals(" "))
        available.setText("Cantidad a prestar");
       if(ejem.getText().equals("") || ejem.getText() == null || ejem.getText().equals(" "))
        ejem.setText("Ingrese la cantidad de ejemplares");
    }//GEN-LAST:event_langMousePressed

    private void langActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_langActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_langActionPerformed

    private void pagesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pagesMousePressed
        if(pages.getText().equals("Ingrese la cantidad de páginas totales"))
        pages.setText("");
       if(id.getText().equals("") || id.getText() == null || id.getText().equals(" "))
        id.setText("Ingrese el ID del Libro");
       if(title.getText().equals("") || title.getText() == null || title.getText().equals(" "))
        title.setText("Ingrese el Título");
       if(date.getText().equals("") || date.getText() == null || date.getText().equals(" "))
        date.setText("Ingrese la Fecha de Publicación");
       if(author.getText().equals("") || author.getText() == null || author.getText().equals(" "))
        author.setText("Ingrese el nombre del Autor/es");
       if(category.getText().equals("") || category.getText() == null || category.getText().equals(" "))
        category.setText("Ingrese la Categoría del Libro");
       if(edit.getText().equals("") || edit.getText() == null || edit.getText().equals(" "))
        edit.setText("Ingrese la edición");
       if(lang.getText().equals("") || lang.getText() == null || lang.getText().equals(" "))
        lang.setText("Ingrese el idioma del Libro");
       if(descr.getText().equals("") || descr.getText() == null || descr.getText().equals(" "))
        descr.setText("Ingrese la descripción del Libro");
       if(stock.getText().equals("") || stock.getText() == null || stock.getText().equals(" "))
        stock.setText("Cantidad Total");
       if(available.getText().equals("") || available.getText() == null || available.getText().equals(" "))
        available.setText("Cantidad a prestar");
       if(ejem.getText().equals("") || ejem.getText() == null || ejem.getText().equals(" "))
        ejem.setText("Ingrese la cantidad de ejemplares");
    }//GEN-LAST:event_pagesMousePressed

    private void pagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pagesActionPerformed

    private void descrMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descrMousePressed
        if(descr.getText().equals("Ingrese la descripción del Libro"))
        descr.setText("");
       if(id.getText().equals("") || id.getText() == null || id.getText().equals(" "))
        id.setText("Ingrese el ID del Libro");
       if(title.getText().equals("") || title.getText() == null || title.getText().equals(" "))
        title.setText("Ingrese el Título");
       if(date.getText().equals("") || date.getText() == null || date.getText().equals(" "))
        date.setText("Ingrese la Fecha de Publicación");
       if(author.getText().equals("") || author.getText() == null || author.getText().equals(" "))
        author.setText("Ingrese el nombre del Autor/es");
       if(category.getText().equals("") || category.getText() == null || category.getText().equals(" "))
        category.setText("Ingrese la Categoría del Libro");
       if(edit.getText().equals("") || edit.getText() == null || edit.getText().equals(" "))
        edit.setText("Ingrese la edición");
       if(lang.getText().equals("") || lang.getText() == null || lang.getText().equals(" "))
        lang.setText("Ingrese el idioma del Libro");
       if(pages.getText().equals("") || pages.getText() == null || pages.getText().equals(" "))
        pages.setText("Ingrese la cantidad de páginas totales");
       if(stock.getText().equals("") || stock.getText() == null || stock.getText().equals(" "))
        stock.setText("Cantidad Total");
       if(available.getText().equals("") || available.getText() == null || available.getText().equals(" "))
        available.setText("Cantidad a prestar");
       if(ejem.getText().equals("") || ejem.getText() == null || ejem.getText().equals(" "))
        ejem.setText("Ingrese la cantidad de ejemplares");
    }//GEN-LAST:event_descrMousePressed

    private void descrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descrActionPerformed

    private void stockMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stockMousePressed
        if(stock.getText().equals("Cantidad Total"))
        stock.setText("");
       if(id.getText().equals("") || id.getText() == null || id.getText().equals(" "))
        id.setText("Ingrese el ID del Libro");
       if(title.getText().equals("") || title.getText() == null || title.getText().equals(" "))
        title.setText("Ingrese el Título");
       if(date.getText().equals("") || date.getText() == null || date.getText().equals(" "))
        date.setText("Ingrese la Fecha de Publicación");
       if(author.getText().equals("") || author.getText() == null || author.getText().equals(" "))
        author.setText("Ingrese el nombre del Autor/es");
       if(category.getText().equals("") || category.getText() == null || category.getText().equals(" "))
        category.setText("Ingrese la Categoría del Libro");
       if(edit.getText().equals("") || edit.getText() == null || edit.getText().equals(" "))
        edit.setText("Ingrese la edición");
       if(lang.getText().equals("") || lang.getText() == null || lang.getText().equals(" "))
        lang.setText("Ingrese el idioma del Libro");
       if(pages.getText().equals("") || pages.getText() == null || pages.getText().equals(" "))
        pages.setText("Ingrese la cantidad de páginas totales");
       if(descr.getText().equals("") || descr.getText() == null || descr.getText().equals(" "))
        descr.setText("Ingrese la descripción del Libro");
       if(available.getText().equals("") || available.getText() == null || available.getText().equals(" "))
        available.setText("Cantidad a prestar");
       if(ejem.getText().equals("") || ejem.getText() == null || ejem.getText().equals(" "))
        ejem.setText("Ingrese la cantidad de ejemplares");
    }//GEN-LAST:event_stockMousePressed

    private void stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockActionPerformed

    private void ejemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ejemMousePressed
        if(ejem.getText().equals("Ingrese la cantidad de ejemplares"))
        ejem.setText("");
       if(id.getText().equals("") || id.getText() == null || id.getText().equals(" "))
        id.setText("Ingrese el ID del Libro");
       if(title.getText().equals("") || title.getText() == null || title.getText().equals(" "))
        title.setText("Ingrese el Título");
       if(date.getText().equals("") || date.getText() == null || date.getText().equals(" "))
        date.setText("Ingrese la Fecha de Publicación");
       if(author.getText().equals("") || author.getText() == null || author.getText().equals(" "))
        author.setText("Ingrese el nombre del Autor/es");
       if(category.getText().equals("") || category.getText() == null || category.getText().equals(" "))
        category.setText("Ingrese la Categoría del Libro");
       if(edit.getText().equals("") || edit.getText() == null || edit.getText().equals(" "))
        edit.setText("Ingrese la edición");
       if(lang.getText().equals("") || lang.getText() == null || lang.getText().equals(" "))
        lang.setText("Ingrese el idioma del Libro");
       if(pages.getText().equals("") || pages.getText() == null || pages.getText().equals(" "))
        pages.setText("Ingrese la cantidad de páginas totales");
       if(descr.getText().equals("") || descr.getText() == null || descr.getText().equals(" "))
        descr.setText("Ingrese la descripción del Libro");
       if(stock.getText().equals("") || stock.getText() == null || stock.getText().equals(" "))
        stock.setText("Cantidad Total");
       if(available.getText().equals("") || available.getText() == null || available.getText().equals(" "))
        available.setText("Cantidad a prestar");
    }//GEN-LAST:event_ejemMousePressed

    private void ejemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ejemActionPerformed

    private void availableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_availableMousePressed
        if(available.getText().equals("Cantidad a prestar"))
        available.setText("");
       if(id.getText().equals("") || id.getText() == null || id.getText().equals(" "))
        id.setText("Ingrese el ID del Libro");
       if(title.getText().equals("") || title.getText() == null || title.getText().equals(" "))
        title.setText("Ingrese el Título");
       if(date.getText().equals("") || date.getText() == null || date.getText().equals(" "))
        date.setText("Ingrese la Fecha de Publicación");
       if(author.getText().equals("") || author.getText() == null || author.getText().equals(" "))
        author.setText("Ingrese el nombre del Autor/es");
       if(category.getText().equals("") || category.getText() == null || category.getText().equals(" "))
        category.setText("Ingrese la Categoría del Libro");
       if(edit.getText().equals("") || edit.getText() == null || edit.getText().equals(" "))
        edit.setText("Ingrese la edición");
       if(lang.getText().equals("") || lang.getText() == null || lang.getText().equals(" "))
        lang.setText("Ingrese el idioma del Libro");
       if(pages.getText().equals("") || pages.getText() == null || pages.getText().equals(" "))
        pages.setText("Ingrese la cantidad de páginas totales");
       if(descr.getText().equals("") || descr.getText() == null || descr.getText().equals(" "))
        descr.setText("Ingrese la descripción del Libro");
       if(stock.getText().equals("") || stock.getText() == null || stock.getText().equals(" "))
        stock.setText("Cantidad Total");
       if(ejem.getText().equals("") || ejem.getText() == null || ejem.getText().equals(" "))
        ejem.setText("Ingrese la cantidad de ejemplares");
    }//GEN-LAST:event_availableMousePressed

    private void availableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_availableActionPerformed

    // SUBIR
    private void buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMousePressed
        if(id.getText().equals("Ingrese el ID del Libro") || title.getText().equals("Ingrese el Título")
            || date.getText().equals("Ingrese la Fecha de Publicación") || author.getText().equals("Ingrese el nombre del Autor/es")
            || category.getText().equals("Ingrese la Categoría del Libro")|| edit.getText().equals("Ingrese la edición")
            || lang.getText().equals("Ingrese el idioma del Libro")|| pages.getText().equals("Ingrese la cantidad de páginas totales")
            || descr.getText().equals("Ingrese la descripción del Libro")|| stock.getText().equals("Cantidad Total")
            || available.getText().equals("Cantidad a prestar")|| ejem.getText().equals("Ingrese la cantidad de ejemplares")){
            javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            id.requestFocus();
        }
        else
        {
            String bid = id.getText();
            String btitle = title.getText();
            String bdate = date.getText();
            String bathor = author.getText();
            String bcategory = category.getText();
            String bedit = edit.getText();
            String blang = lang.getText();
            String bpages = pages.getText();
            String bdescr = descr.getText();
            String bstock = stock.getText();
            String bavailable = available.getText();
            String bejem = ejem.getText();
            int pag=0;
            int stc=0;
            int av=0;

            if(bid == null || "".equals(bid) || btitle == null || "".equals(btitle) || bdate == null || "".equals(bdate) 
                    || bathor == null || "".equals(bathor) || bcategory == null || "".equals(bcategory) 
                    || bedit == null || "".equals(bedit) || blang == null || "".equals(blang) || bpages == null || "".equals(bpages) 
                    || bdescr == null || "".equals(bdescr) || bstock == null || "".equals(bstock) 
                    || bavailable == null || "".equals(bavailable) || bejem == null || "".equals(bejem)){
                javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                id.requestFocus();
            }
            else{ 
                try{
                    pag = Integer.parseInt(bpages);
                    stc = Integer.parseInt(bstock);
                    av = Integer.parseInt(bavailable);

                    try {
                        if(edition)
                            EditBook(bid, btitle, bdate, bathor, bcategory, bedit, blang, pag, bdescr, stc, av, bejem);
                        else
                            InsertBook(bid, btitle, bdate, bathor, bcategory, bedit, blang, pag, bdescr, stc, av, bejem);

                        id.setText("");
                        title.setText("");
                        date.setText("");
                        author.setText("");
                        category.setText("");
                        edit.setText("");
                        lang.setText("");
                        pages.setText("");
                        descr.setText("");
                        stock.setText("");
                        available.setText("");
                        ejem.setText("");

                        if(edition){
                            Books p1 = new Books();
                            p1.setSize(750, 430);
                            p1.setLocation(5, 5);

                            content.removeAll();
                            content.add(p1, BorderLayout.CENTER);
                            content.revalidate();
                            content.repaint();
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(UpUsers.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }catch(NumberFormatException ex){
                    javax.swing.JOptionPane.showMessageDialog(this, "Las páginas, el Stock y el Disponible, deben ser números enteros. \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    id.requestFocus();
                }

            }
        }
    }//GEN-LAST:event_buttonMousePressed

    void setColor(JPanel panel){
        panel.setBackground(new Color(21,101,192));
    }
    void resetColor(JPanel panel){
        panel.setBackground(new Color(18,90,173));
    }
    
    public void InsertBook(String id, String titu, String fech, String auth, String cate, String ed, String idiom, int pags, String desc, int stck, int avai, String ej) throws SQLException{
        Statement stm = reg.createStatement();
        
        stm.executeUpdate("INSERT INTO `books` (`id`, `title`, `date`, `author`, `category`, `edit`, `lang`, `pages`, `description`, `ejemplares`, `stock`, `available`) VALUES ('"+id+"', '"+titu+"', '"+ fech +"', '"+ auth +"', '"+cate+"', '"+ed+"', '"+idiom+"', '"+pags+"', '"+desc+"', '"+ej+"', '"+stck+"', '"+avai+"')");
        javax.swing.JOptionPane.showMessageDialog(this, "¡Libro registrado correctamente! \n", "HECHO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        
    }
    
    public void EditBook(String id, String titu, String fech, String auth, String cate, String ed, String idiom, int pags, String desc, int stck, int avai, String ej) throws SQLException{
        Statement stm = reg.createStatement();
        
        stm.executeUpdate("UPDATE `books` SET `id` = '"+id+"', `title` = '"+titu+"', `date` = '"+fech+"', `author` = '"+auth+"', `category` = '"+cate+"', `edit` = '"+ed+"', `lang` = '"+idiom+"', `pages` = '"+pags+"', `description` = '"+desc+"', `ejemplares` = '"+ej+"', `stock` = '"+stck+"', `available` = '"+avai+"' WHERE `id` = '"+ origId +"';");
        javax.swing.JOptionPane.showMessageDialog(this, "¡Libro editado correctamente! \n", "HECHO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Text10;
    private javax.swing.JLabel Text11;
    private javax.swing.JLabel Text12;
    private javax.swing.JLabel Text13;
    private javax.swing.JLabel Text14;
    private javax.swing.JLabel Text15;
    private javax.swing.JLabel Text3;
    private javax.swing.JLabel Text4;
    private javax.swing.JLabel Text6;
    private javax.swing.JLabel Text7;
    private javax.swing.JLabel Text8;
    private javax.swing.JLabel Text9;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField author;
    private javax.swing.JTextField available;
    private javax.swing.JPanel body;
    private javax.swing.JPanel button;
    private javax.swing.JTextField category;
    private javax.swing.JTextField date;
    private javax.swing.JTextField descr;
    private javax.swing.JTextField edit;
    private javax.swing.JTextField ejem;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField lang;
    private javax.swing.JTextField pages;
    private javax.swing.JTextField stock;
    private javax.swing.JTextField title;
    // End of variables declaration//GEN-END:variables
}
